version: '3'
tasks:
  serve:
    cmd: go run cmd/user-service/main.go cmd/user-service/grpc.go
  protoc:
    cmd:
      protoc
      --go_out=.
      --go_opt=paths=source_relative
      --go-grpc_out=.
      --go-grpc_opt=paths=source_relative
      internal/proto/user.proto